// 이어서 풀기: 새로고침·창 닫기 뒤에도 연습 진행과 시험 답안이 남는지
const { launch, sleep } = require("./cdp.js");
const os = require("os");
const ROOT = require("url").pathToFileURL(require("path").join(__dirname, "..", "..")).href + "/";
let pass = 0, fail = 0;
const ok = (c, m) => { if (c) { pass++; console.log("  ✓", m); } else { fail++; console.log("  ✗", m); } };
(async () => {
  const b = await launch(9506, os.tmpdir() + "/tsw6");
  const p = await b.newPage();
  const wait = (e, ms) => p.waitFor(e, ms || 10000);
  console.log("1) 연습 중간에 새로고침");
  await p.goto(ROOT + "practice.html?start=1&part=5&level=3&n=3");
  await wait("location.pathname.endsWith('solve.html')");
  const url = await p.eval("location.href");
  await wait("document.querySelector('.choice')");
  await p.eval("document.querySelectorAll('.choice')[0].click()");
  await wait("document.querySelector('.explain')");
  await p.goto(url);
  await wait("document.querySelector('.choice')");
  const prog = await p.eval("document.getElementById('progress').innerText");
  ok(/1 \/ 3문항 채점/.test(prog), "새로고침 뒤 진행 유지: " + prog);
  ok(await p.eval("!document.querySelector('.explain')"), "다음 안 푼 문제로 이어짐");
  await p.goto(ROOT + "toeic.html");
  await wait("document.querySelector('.kpi')");
  ok(await p.eval("document.body.innerText.includes('이어서 풀기')"), "오늘 화면에 '이어서 풀기'");

  console.log("2) 시험 중 새로고침: 답안 유지");
  const sid = await p.eval("(async () => await Sessions.startMock('mini', TSU.makeRng(4)))()");
  await p.goto(ROOT + `solve.html?sid=${sid}`);
  await wait("document.getElementById('start-btn')");
  await p.eval("TTS.stop = () => {}; TTS.play = async () => true");
  await p.click("#start-btn");
  await wait("document.querySelector('.choice')");
  await p.eval("document.querySelectorAll('.choices').forEach(c => c.querySelector('.choice').click())");
  await p.eval("document.querySelector('[data-act=next]').click()");
  await wait("document.querySelector('.choice')");
  await p.eval("document.querySelectorAll('.choices').forEach(c => c.querySelectorAll('.choice')[1].click())");
  await sleep(300);
  const before = await p.eval("document.getElementById('progress').innerText");
  await p.eval("window.onbeforeunload = null");
  await p.goto(ROOT + `solve.html?sid=${sid}`);
  await wait("document.getElementById('start-btn')");
  await p.eval("TTS.stop = () => {}; TTS.play = async () => true");
  await p.click("#start-btn");
  await wait("document.querySelector('.choice')");
  const after = await p.eval("document.getElementById('progress').innerText");
  ok(before === after && /문항 답함/.test(after), `답안 유지: ${before} → ${after}`);
  ok(await p.eval("document.querySelector('.item-head').innerText.includes('2 /')"), "보던 문제 위치(2번째 묶음)로 복귀");
  console.log("콘솔 오류:", p.logs.join(" / ") || "(없음)");
  console.log(`통과 ${pass} / 실패 ${fail}`);
  b.close();
  process.exit(fail ? 1 : 0);
})().catch(e => { console.error("중단:", e.message); process.exit(1); });
